[tool.poetry]
name = "sus"
version = "0.0.1"
description = "sus: Really simple static website URL shortener"
license = "MIT"
authors = ["Nik Kantar <nik@nkantar.com>"]
readme = "README.rst"
homepage = "https://github.com/nkantar/sus"
repository = "https://github.com/nkantar/sus"
documentation = "https://github.com/nkantar/sus"

packages = [
  { include = "src" }
]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^6.0.1"
pytest-watch = "^4.2.0"
pytest-mock = "^3.2.0"

[scripts]
sus = "src.sus:sus"

[build-system]
requires = ["setuptools >= 49.6.0", "wheel"]
build-backend = "setuptools.build_meta"
